### PR TITLE
Add meta-world example

### PR DESCRIPTION
**Pull request by Kostis-S-Z**
### MAML-TRPO on Meta-world

A simple MAML-TRPO example on the new meta-learning multi-tasking benchmark environment [**Meta-world**](https://github.com/rlworkgroup/metaworld)

This example inherits its structure from the `maml_trpo.py` file. However, due to some unresolved issues it currently does *not* work for more than 1 worker in parallel.

In the `main()` function through the `benchmark` parameter, the user can choose to test the code on the 3 benchmark environments of Meta-world: ML1, ML10, ML45. Currently, the results for ML1 seem stable and working. The other benchmarks probably require more tweaking & computation.

### Contribution Checklist

If your contribution modifies code in the core library (not docs, tests, or examples), please fill the following checklist.

- [ ] My contribution modifies code in the main library.
- [x] My modifications are tested.
- [ ] My modifications are documented.

### CODE REVIEW

**Comment by Kostis-S-Z** [comment]
Actually there is an issue with this implementation. 
**Every task can only sample one episode of 150 steps.**

#### Meta-world background limitation
The meta-world environments have a horizon of 150steps (some have 200steps) but the environment itself does not send a "done" signal when it reaches the end of it (see [this issue](https://github.com/rlworkgroup/metaworld/issues/60)). So if we do not manually set the episode length to be 150 steps like this:
`train_episodes = task.run(clone, steps=150)`
we will get:
`ValueError: Maximum path length allowed by the benchmark has been exceeded`

#### Cherry Runner limitation
However, by setting a fixed length of the episode we cannot sample more than one episode. Ideally, we would like to do this:
`train_episodes = task.run(clone, steps=150, episodes=adapt_batch_size)`
but the l2l Runner is not happy with this and raises
`Exception: Either steps or episodes should be set.`

#### Possible solution 1 (without modifying cherry but maybe not very elegant)
We can call the runner in a loop to collect the episodes we want. So from this
```
for step in range(adapt_steps):
    train_episodes = task.run(clone, steps=150)
    clone = fast_adapt_a2c(clone, train_episodes, ...)
    task.env.reset()
    task_replay.append(train_episodes)
```
modify it like this:
```
for step in range(adapt_steps):
    train_episodes = ch.ExperienceReplay()
    for episode in range(self.params['adapt_batch_size']):
        train_episode = task.run(clone, steps=150)
        train_episodes.__iadd__(train_episode)
        task.env.reset()
    clone = fast_adapt_a2c(clone, train_episodes, ...)
    task_replay.append(train_episodes)
```

#### Possible solution 2 (requires modifying cherry)
The only thing needed in this case would be that cherry could support both limiting the length of an episode and collecting multiple episodes at the same time. Maybe this could be useful for other settings as well? I would like to hear your thoughts on this!

**Comment by Kostis-S-Z** [comment]
I updated the example with the first solution I proposed above. Let me know if I should change something else as well.

**Comment by seba-1511** [comment]
Even better, thank you @Kostis-S-Z .

Regarding solution 1, is there a reason for using `episodes.__iadd__(episode)` instead of `episodes += episode` ? I think the two should behave identically, but the latter is more pythonic.

For solution 2, a simple fix is to have an environment wrapper that limits the horizon. This would naturally fit in cherry, and avoids the confusion of passing both `steps` and `episodes` to `Runner`. (e.g. should we take the min of the steps/episodes? The max?)

**Comment by Kostis-S-Z** [comment]
I will look into making a wrapper since it will help with parallelizing the environment as well. Maybe we can leave the PR open until then as well, whatever you prefer.

> Regarding solution 1, is there a reason for using episodes.__ iadd __(episode) instead of episodes += episode ? I think the two should behave identically, but the latter is more pythonic.

No reason at all, other than my being a bit hasty! Fixed!

**Pull request closed without merging**
