### PR TITLE
Add keep_requires_grad flag to detach_module

### PR DESCRIPTION
**Pull request by ZhaofengWu**
### Description

Discussed in slack.

Replace this line by a one sentence summary of your PR.

If necessary, use the following space to provide context or more details.

### Contribution Checklist

If your contribution modifies code in the core library (not docs, tests, or examples), please fill the following checklist.

- [x] My contribution is listed in CHANGELOG.md with attribution.
- [x] My contribution modifies code in the main library.
- [x] My modifications are tested.
- [x] My modifications are documented.

#### Optional

If you make major changes to the core library, please run `make alltests` and copy-paste the content of `alltests.txt` below.

There seem to be some import errors, but I also get those errors on upstream master. So I suspect I might be able to ignore those. Let's see if the github CI tests pass.

### CODE REVIEW

**Comment by seba-1511** [comment]
Thanks @ZhaofengWu, this looks great.

It seems like there's one linting error (`make lint`). Once that's fixed we can merge it.

**Comment by ZhaofengWu** [comment]
Fixed. Once you approve running the workflow we can see if there are other issues.

**Comment by ZhaofengWu** [comment]
The error doesn't seem like coming from this PR -- maybe some CI config issue?

**Comment by seba-1511** [comment]
Yes, seems unrelated to this PR. Thanks, merging now.

**Pull request merged**
